apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: modresort-route
  namespace: modresort-entitlement-5
  annotations:
    app.ibm.com/is-local-deployable: "false"
    app.ibm.com/deployable-version: 1.0.0    
  labels:
    app: modresort-app
spec:
  template:
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: modresort-app
      name: modresort-route
    spec:
      port:
        targetPort: 9080
      subdomain: ""
      to:
        kind: Service
        name: modresort-service
        weight: 100
      wildcardPolicy: None
