apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: modresort-service
  namespace: modresort-entitlement-5
  annotations:
    app.ibm.com/is-local-deployable: "false"
    app.ibm.com/deployable-version: 1.0.0    
  labels:
    app: modresort-app
    component: main
    package: modresort
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: modresort-service
      labels:
        app: modresort-app
    spec:
      type: NodePort
      ports:
        - port: 9080
      selector:
        app: modresort-app
        tier: frontend
