apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: modresort-route
  labels:
    app: modresort-app
spec:
  port:
    targetPort: 9080
  subdomain: ""
  to:
    kind: Service
    name: modresort-service
    weight: 100
  wildcardPolicy: None
